setcompatiblemode 0x20000;

#isReg = no;

if ( selecting ) {
	$seltext = gettext(seltopx, seltopy, selendx, selendy);
} else {
	$seltext = "";
	question "³‹K•\Œ»‚ÅŒŸõ‚µ‚Ü‚·‚©H";
	#isReg = result;
}
$keyword = input("ŒŸõ•¶Žš—ñ‚ð“ü—Í", $seltext);

if ( strlen($keyword) > 0 ) {
	if ( #isReg == yes ) {
		localgrep $keyword, regular;
	} else {
		localgrep $keyword;
	}
}

endmacro;
